name: 🎨 AnasWZMLrclone-Mirror

on:
  workflow_dispatch:
    inputs:
      CONFIG_FILE_URL:
        description: 'gist.githubusercontent.com မှ config.envနှင့်ဆုံးသောlink'
        required: true
jobs:
  Starting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Image
        run: docker pull anasaty17/allinonemltb
      - name: Run Image
        run: docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL }} anasaty17/allinonemltb
